# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
