# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20180127_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pos.Member'),
        ),
    ]
