# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20180201_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='all_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='all_washed',
            field=models.BooleanField(default=False),
        ),
    ]
